stages:
  - standard-test
  - api-test
  - deploy-prod

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://docker:2375"

dev-commit-test:
  stage: standard-test
  image: node:10.17.0
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
    - merge_requests
  script:
    - cd ./
    - npm install --save-dev commitlint @commitlint/config-conventional
    - git fetch origin master
    - ./node_modules/.bin/commitlint --color --verbose --from=$(git rev-parse remotes/origin/master)

dev-codingstyle-test:
  stage: standard-test
  image: node:10.17.0
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
    - merge_requests
  script:
    - cd ./app
    - npm install
    - npm run styletest
    - cd ../
    - cd ./apitest
    - npm install
    - npm run styletest

dev-api-test:
  stage: api-test
  image: docker/compose:alpine-1.29.1
  only:
    - merge_requests
  services:
    - docker:19.03.0-dind
  before_script:
    - cat /etc/*elease
  script:
    - docker ps
    - echo "Start to exec testings"
    - docker-compose down -v
    - docker-compose up -d
    - sleep 30
    - docker exec -i mll-apitest npm run apitest

prod-deploy:
  stage: deploy-prod
  tags:
    - sdm2021group3-prodssh
  only:
    - web
  script:
    - pwd
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml down -v
    - echo "start services"
    - mkdir -p app/node_modules/ app/node_modules/.cache/
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
    - echo "remove unused services"
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml stop mll-apitest
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml rm -f mll-apitest
    - echo "check logs"
    - sleep 30
    - docker-compose -f docker-compose.yml -f docker-compose.prod.yml logs mll-api
