stages:
  - standard-test
  - api-test
  - deploy-prod

dev-commit-test:
  stage: standard-test
  image: sdm2021group3-ci:1.0
  tags:
    - sdm2021group3-docker
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
    - merge_requests
  script:
    - git fetch origin master
    - commitlint --color --from=$(git rev-parse remotes/origin/master)

dev-codingstyle-test:
  stage: standard-test
  image: sdm2021group3-ci:1.0
  tags:
    - sdm2021group3-docker
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
    - merge_requests
  script:
    - cd ./app
    - eslint --ext .js ./ --color
    - cd ../
    - cd ./apitest
    - eslint --ext .js ./ --color

dev-api-test:
  stage: api-test
  tags:
    - sdm2021group3-ssh
  only:
    - merge_requests
  script:
    - docker-compose down -v
    - docker-compose up -d
    - sleep 30
    - docker exec -i mll-apitest npm run apitest

prod-deploy:
  stage: deploy-prod
  tags:
    - sdm2021group3-prodssh
  only:
    - web
  script:
    - pwd
    - docker-compose down -v
    - echo "start services"
    - mkdir -p app/node_modules/ app/node_modules/.cache/
    - docker-compose up -d
    - echo "remove unused services"
    - docker-compose stop mll-apitest
    - docker-compose rm -f mll-apitest
    - echo "check logs"
    - sleep 30
    - docker-compose logs mll-api
