stages:
  - standard-test
  - api-test

dev-commit-test:
  stage: standard-test
  image: sdm2021group3-ci:1.0
  tags:
    - sdm2021group3-docker
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
  script:
    - commitlint --color --from=$(git rev-parse remotes/origin/master)

dev-codingstyle-test:
  stage: standard-test
  image: sdm2021group3-ci:1.0
  tags:
    - sdm2021group3-docker
  only:
    - /^feature\/.*$/
    - /^bugfix\/.*$/
    - /^test\/.*$/
  script:
    - cd ./app
    - eslint --ext .js ./ --color
    - cd ../
    - cd ./apitest
    - eslint --ext .js ./ --color

dev-api-test:
  stage: api-test
  tags:
    - sdm2021group3-ssh
  only:
    - triggers
  script:
    - docker-compose down -v
    - docker-compose up -d
    - sleep 30
    - docker exec -i mll-apitest npm run apitest
