version: "2.4"

networks:
   mll-backend-net:
        name: mll-backend-net

services:
    mll-mysql:
        extends:
            file: docker-compose.base.yml
            service: mll-mysql
    mll-api:
        extends:
            file: docker-compose.base.yml
            service: mll-api
        volumes:
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
            - /home/runner/mll-cert/ssl.crt:/localhost.crt:ro
            - /home/runner/mll-cert/ssl.key:/localhost.key:ro
        command: ["sh", "-c", "npm install && \
            STAGE=prod \
            SSL_CERT_FILE=/localhost.crt \
            SSL_KEY_FILE=/localhost.key \
            npm run start"]
        depends_on:
            - mll-mysql
    mll-phpmyadmin:
        extends:
            file: docker-compose.base.yml
            service: mll-phpmyadmin
        ports:
            - "8080:80"
