version: "2.4"

networks:
   mll-backend-net:
        name: mll-backend-net

services:
    mll-mysql:
        extends:
            file: docker-compose.base.yml
            service: mll-mysql
        volumes:
            - ./db:/docker-entrypoint-initdb.d
    mll-api:
        extends:
            file: docker-compose.base.yml
            service: mll-api
        volumes:
            - ./app:/app
            - ./localhost.crt:/localhost.crt
            - ./localhost.key:/localhost.key
        ports:
            - "${APP_PORT}:8181"
        depends_on:
            - mll-mysql
    mll-phpmyadmin:
        extends:
            file: docker-compose.base.yml
            service: mll-phpmyadmin
        ports:
            - "8080:80"
    mll-apitest:
        image: node:10.17.0
        container_name: mll-apitest
        volumes:
            - ./apitest:/apitest
        environment:
            NODE_TLS_REJECT_UNAUTHORIZED: 0
            TZ: Asia/Taipei
        networks:
            - mll-backend-net
        working_dir: /apitest
        command: ["sh", "-c", "npm install && tail -F /dev/null"]
