version: "2.4"

networks:
   mll-backend-net:
        name: mll-backend-net

services:
    mll-mysql:
        image: mysql:5.6.51
        container_name: mll-mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: P@ssWd
            MYSQL_DATABASE: mllapp
            MYSQL_USER: app
            MYSQL_PASSWORD: mllapp
            TZ: Asia/Taipei
        command:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
        networks:
            - mll-backend-net
    mll-api:
        image: node:10.17.0
        container_name: mll-api
        restart: always
        environment:
            TZ: Asia/Taipei
        networks:
            - mll-backend-net
        working_dir: /app
        command: ["sh", "-c", "npm install && \
            SSL_CERT_FILE=/localhost.crt \
            SSL_KEY_FILE=/localhost.key \
            npm run start"]
    mll-phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: mll-phpmyadmin
        restart: always
        environment:
            PMA_HOST: mll-mysql
            PMA_PORT: 3306
            TZ: Asia/Taipei
        networks:
            - mll-backend-net
